#define PHP_FFI_TOK_ASTERISK                        1
#define PHP_FFI_TOK_CALLBACK                        2
#define PHP_FFI_TOK_COMMA                           3
#define PHP_FFI_TOK_EQUALS                          4
#define PHP_FFI_TOK_IDENT                           5
#define PHP_FFI_TOK_INTRINSIC                       6
#define PHP_FFI_TOK_LBRACE                          7
#define PHP_FFI_TOK_LPAREN                          8
#define PHP_FFI_TOK_LSQUARE                         9
#define PHP_FFI_TOK_RBRACE                         10
#define PHP_FFI_TOK_RPAREN                         11
#define PHP_FFI_TOK_RSQUARE                        12
#define PHP_FFI_TOK_SEMI                           13
#define PHP_FFI_TOK_STRING                         14
#define PHP_FFI_TOK_STRUCT                         15
#define PHP_FFI_TOK_TYPEDEF                        16
